### ISSUE TITLE
Unexpected string in JSON at position 43

### ISSUE THREAD

**Issue by sbursik** [maatt/gurushots-auto-vote-and-boost#3]
When launching nodemon complains about syntax in the config.json. Looks like the @ sign is an issue?

`scott@ScottsDesktop:/mnt/c/GurushotsVoter$ sudo npm start

> gurushot-voter@1.0.0 start /mnt/c/GurushotsVoter
> nodemon main.js

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node main.js`
internal/modules/cjs/loader.js:800
    throw err;
    ^

SyntaxError: /mnt/c/GurushotsVoter/config.json: Unexpected string in JSON at position 43
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:797:27)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/c/GurushotsVoter/main.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by sbursik** [comment]
Disregard, I had a comma missing at the end of the username line
